server:
  port: 9527

spring:
  application:
    name: springcloud-06-zuul-geteway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**
  #ignored-services: springcloud-dept  #忽略原真是服务名
  ignored-services: "*"
  prefix: /afcat


info:
  app.name: afcat-springcloud
  company.name: www.baidu.com
  build.artifacId: $project.artifactId$
  build.version: $project.version$


